name: fkingtest
favicon: null
layout_spectrum: 0.5714654598850757
typography_spectrum: 0.5687422568444163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5546508147381246
  lightness: 0.3467557623516768
  saturation: 0.8878252552822232
  rhythmicContrast: 0.44280973309651017
purpose: []
