name: fkingtest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#614f5f'
    - '#cfcfd1'
    - '#29343c'
    - '#dc8471'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.8878252552822232
  rhythmicContrast: 0.75
purpose: []
